import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const interSans = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const serif = localFont({
  variable: "--font-serif",
  src: "../font/6f324551b041d4dd-s.p.woff2",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="dark" lang="en">
      <body
        className={`${interSans.variable} ${serif.variable} antialiased text-primary`}
      >
        {children}
      </body>
    </html>
  );
}
